
= raft

== 应用

. etcd 2

== 共识算法

共识是可容错系统中的一个基本问题：即使面对故障，服务器也可以在共享状态上达成一致。

== 节点类型

. Leader

    负责发起心跳，响应客户端，创建日志，同步日志。

. Candidate

    Leader 选举过程中的临时角色，由 Follower 转化而来，发起投票参与竞选。

. Follower

    接受 Leader 的心跳和日志同步数据，投票给 Candidate。


raft 算法将时间划分为任意长度的任期（term），任期用连续的数字表示，看作当前 term 号。

每一个任期的开始都是一次选举

- 每个节点都会存储当前的 term 号，当服务器之间进行通信时会交换当前的 term 号；
- 如果有服务器发现自己的 term 号比其他人小，那么他会更新到较大的 term 值。
- 如果一个 Candidate 或者 Leader 发现自己的 term 过期了，他会立即退回成 Follower。
- 如果一台服务器收到的请求的 term 号是过期的，那么它会拒绝此次请求。

由于可能同一时刻出现多个 Candidate，导致没有 Candidate 获得大多数选票，如果没有其他手段来重新分配选票的话，那么可能会无限重复下去。

raft 使用了随机的选举超时时间来避免上述情况。每一个 Candidate 在发起选举后，都会随机化一个新的枚举超时时间，这种机制使得各个服务器能够分散开来，在大多数情况下只有一个服务器会率先超时；它会在其他服务器超时之前赢得选举。

== 日志复制

一般情况下，Leader 和 Follower 的日志保持一致，然后，Leader 的崩溃会导致日志不一样，这样一致性检查会产生失败。Leader 通过强制 Follower 复制自己的日志来处理日志的不一致。这就意味着，在 Follower 上的冲突日志会被领导者的日志覆盖。

== 安全性

=== 选举限制

每个 Candidate 发送 RequestVoteRPC 时，都会带上最后一个 entry 的信息。所有节点收到投票信息时，会对该 entry 进行比较，如果发现自己的更新，则拒绝投票给该 Candidate。

判断日志新旧的方式：如果两个日志的 term 不同，term 大的更新；如果 term 相同，更长的 index 更新。
